- template/fabric8-online-che-openshift.yml
- template/fabric8-online-jenkins-openshift.yml
@aslakknutsen this should help normalise the Jenkins resources; we setup a 90Mi claim as minimal to make sure small stuff like the content cache etc can work. Max'ing out Jenkins itself at 700Mi, it should not need anything more than that. Also moving the terminating=jobs to be 1Gi max, since most builds would not need this much ram.
@vpavlin once @aslakknutsen has this in, can you sync your account ( rebuild ? ) and validate.
> Resource limits jenkins

- template/fabric8-online-che-openshift.yml
This setup has to be used when che workspaces are deployed as non-terminating pods (that's currently the only option).
And for the love of code duplication...https://github.com/fabric8io/fabric8-online/pull/118
> New configuration to make Che work on new int environment

- template/fabric8-online-che-openshift.yml
at the moment, che cant support https, so lets not use it in the template. unsure how this ever passed any kind of testing.
> dont use https for che till che can support https

- openshift/init_tenant.go
currently when running on minishift we have to disable host verification to be able to run `oc apply`
> fix(minishift): lets allow configurable host verification

- openshift/kube_token.go
support vanilla kubernetes for init tenant
> lets allow the exposer to be configured via env var on k8s

- controller/tenant.go
- openshift/init_tenant.go
Rely on Async REST method to init Che and Jenkins,
while using oc apply on Che and Jenkins update.
REST method is a lot faster, and since there is nothing
to update at this point we can do a simple brute force POST/DELETE/POST
session.
* Removed Reorder of templates since they now come ordered from upstream.
Fixes #167
> Split init and update strategy

- controller/tenant_kube.go
- main.go
- openshift/kube_keycloak.go
if for some reason the tenant did not get setup before we go to _gettingstarted lets ensure that the tenant gets setup or updated so that the jenkins namespace is setup before checking the jenkins redirectURI is populated correctly
> lazily setup or update the tenant for kubernetes

- controller/tenant.go
- controller/tenant_kube.go
- openshift/apply.go
- openshift/init_tenant.go
- openshift/process_template.go
* DELETE admin role in namespce 'user' on init
All other changes are reflected in the templates.
Update now assumes namespaces will be there and will not
recreate them. Each namespace is updated via oc apply in parallel.
> Lock down access to the users namespaces

- template/generate_test.go
Fabric8-Maven-Plugin does not separate between the parameters
required in the Openshift and the K8 templates. Even tho
the new parameter is not used in the Openshfit templates it's
defined in the template spec.
> Add +1 addition parameter to teams template test

- Dockerfile.dev
- openshift/kube_keycloak.go
fixes https://github.com/fabric8-services/fabric8-auth/issues/91
by ensuring these settings are preserved during the update of the jenkins redirect URI
> ensure remote resource management is enabled on keycloak for k8s

- configuration/configuration.go
CheHost require half a URL configured, not just base.
https://github.com/fabric8-services/fabric8-tenant-che/pull/60#pullrequestreview-75477878
Related to fabric8-services/fabric8-tenant-che#60
> Quick fix for Che SSO URL

- .gitignore
- configuration/configuration.go
- glide.lock
- glide.yaml
- main.go
- openshift/init_tenant.go
- openshift/process_template.go
- template/generate.go
- template/generate_test.go
- toggles/toggles.go
Toggle deploy.che-multi-tenant is used during rollout period.
Related to redhat-developer/rh-che#404
> Add support for Multi Tenant Che tenant install

- configuration/configuration.go
- openshift/process_template.go
- template/generate_test.go
These 2 values should be added to the config map that will be read by the run-once POD that will do the single-tenant to multi-tenant migration.
This PR is a followup of this one: https://github.com/fabric8-services/fabric8-tenant-che/pull/74/files and should be merged one the latter is merged
> Add `requestId` and `identityId` to the template variables for the Che migration job POD

- controller/tenant.go
- main.go
- token/auth_service_account.go
- token/users.go
- token/users_test.go
auth /api/user calls tenant setup calls auth /api/user...
Related to openshiftio/openshift.io#1687
> Call /api/users/id to avoid endless loop with auth

- configuration/configuration.go
- glide.lock
- glide.yaml
- main.go
Metrics are exposed under /metrics and the used port
can be controlled via F8_METRICS_HTTP_ADDRESS. By
default same port as F8_HTTP_ADDRESS is used.
> Expose basic go runtime metrics via Prometheus

- controller/tenant.go
- controller/tenant_test.go
Only certain users should have access to override the tenant
profile in production. Locked down to the feature group internal.
Fixes #495
> Use whitelist to restrict permission to user profile override

- cluster/service.go
- test/data/cluster/resolve_cluster.yaml
`auth-service` stores the clusters' service account tokens in an encrypted
form and it cannot decrypt them (only `tenant-service` can do it), so it
is not able to validate the tokens. This will have to be done by the
`tenant-service` once the cluster tokens have been retrieved and
decoded.
> Disable 'pullForce=true' when retrieving cluster SA token (OSIO#2304)

- controller/tenant.go
- openshift/apply.go
- openshift/init_tenant.go
Jenkins template is too large for the fluentd log monitor to consume as 1 line which splits up the log line over 4 lines. 
Reverts fabric8-services/fabric8-tenant#562
> Revert "Log requested update template"

- OpenShiftTemplate.yml
Restrict how much memory the container can consume.
Limit to avoid it overtaking the cluster if the process were to go rogue.
Related to openshiftio/openshift.io#2685
> Set resource limits on Container level

- auth/auth_client.go
- cluster/service.go
- jsonapi/jsonapi_utility.go
- jsonapi/jsonapi_utility_blackbox_test.go
- token/sa_service.go
- token/service.go
- user/user_service.go
Set the JSON-API error `ID` with the `NotFoundError.ID` value.
Fixes #573
> Include tenant id in "Not found" error response (#573)

- cico_build_deploy.sh
The build script is being run twice, one to build the CentOS container. The second one for the RHEL container.
On the second run, it fails:
```
Docker container "fabric8-tenant-local-build" already exists. To recreate, run "make docker-rm".
+ make docker-check-go-format
docker exec -t -i "fabric8-tenant-local-build" bash -ec 'make check-go-format'
ERROR: These files differ from gofmt's style (run 'make format-go-code' to fix this):
./migration/sqlbindata.go
make: *** [check-go-format] Error 1
```
It is completely unnecessary to run through the steps twice. That's why in this commit the preparation steps are only executed if they haven't been executed before.
> Skip the build on the second time the script is run

- Gopkg.lock
- Gopkg.toml
- cluster/service.go
- cluster/service_test.go
- controller/tenant.go
- controller/tenant_test.go
- design/tenant.go
- test/data/cluster/resolve_cluster.yaml
Now when calling `/api/tenant` and `/api/tenants`, now the namespaces
information that is returned by tenant service will also include an
attribute `cluster-capacity-exhausted` which is a boolean which
indicates if the cluster this namespace is hosted on has exhausted it's
resources or is still capable of running more workloads.
Taking stab at https://github.com/openshiftio/openshift.io/issues/3320
> add capacity flag to namespaces

- Gopkg.lock
- cluster/service_test.go
- controller/tenant.go
- controller/tenants.go
- controller/tenants_test.go
- design/tenant.go
- main.go
- openshift/clean_tenant.go
- openshift/service.go
- openshift/whoami.go
- openshift/whoami_test.go
- tenant/repository.go
- test/data/controller/delete-tenants-204.yaml
- test/data/controller/delete-tenants-403.yaml
- test/data/controller/delete-tenants-500.yaml
- test/data/controller/search-tenants.yaml
- test/data/controller/show-tenants.yaml
- test/jwt_token.go
- test/recorder/recorder.go
- token/service_test.go
- user/user_service.go
Refactored the `tenants` controller to include a new `openshift`
service that provides a method to delete a namespace using the
OSO API. This service can use a different HTTP client transport,
which allows for testing with the `go-vcr` library.
If a namespace deletion fails, the whole deletion stops, except for
`403 Forbidden` responses from OSO which can be returned if the
namespace to delete does not exist. In that case, there's no reason
to halt the tenant deletion.
Fixes openshiftio/openshift.io#3338
> API to delete/deprovision a user from Tenant (OSIO#3338)

- Dockerfile.deploy.rhel
- OpenShiftTemplate.yml
- cico_setup.sh
This PR is part of the effort to move to Quay.
This is the list of changes in this PR:
- Pushes to Quay instead of the Devshift registry
- Uses an image hosted in Quay to build the RHEL based container image
- Uses the new env-toolkit to load variables from jenkins-env
- Changes the default path of the image to quay (note that this should not affect production because it is overridden in the saas repo)
A companion PR should have been submitted to the appropriate saas repo to change the staging url from devshift to quay. The PR to the saas repo should be merged before this one.
https://github.com/openshiftio/saas-openshiftio/pull/914
> Move to Quay.io

- Gopkg.lock
- controller/tenant.go
- openshift/init_tenant.go
- tenant/tenant.go
- tenant/tenant_test.go
fix to cover the cases when a username ends with any of `-run` `-stage` `-test` `-che `-jenkins` suffixes. otherwise, the tenant service assumes that the user namespace (that has the same name as the username is) is of any other type than the user one.
> fix: detect user ns when has same name as the username is

- .make/Makefile.lnx
- .make/test.mk
- Makefile
- controller/tenant.go
- environment/service.go
- environment/service_test.go
- environment/template.go
- environment/template_test.go
- main.go
- openshift/apply_test.go
- openshift/config.go
- openshift/init_tenant_test.go
- openshift/process_template.go
This PR is a followup of a PR https://github.com/fabric8-services/fabric8-tenant/pull/634. It changes the template versioning system to a form we agreed on in a mailing thread - that as a template version a `sha` of the latest commit that changes the particular file is used. This is set by `LDFLAGS`. The correct creation of the `LDFLAGS` is verified by a test that is executed as part of `test-unit` target:
> Use sha of latest commit that changes a template file as its version

- environment/service.go
- environment/service_test.go
For downloading templates files (in case of in-production testing) the host `raw.githubusercontent.com` is used. It also checks if the custom repo URL (set in _profile page) contains `github.com` host and replaces it by the correct one.
I have changed the mocked tests to verify the host and also added another test (that is by default excluded) that downloads the templates from a specific blob directly from GitHub - by un-excluding the test it is easy to verify that the downloads are really working
> fix(#655): use raw.githubusercontent.com host for downloading template files

- environment/templates/fabric8-tenant-jenkins.yml
This patch removes auto starting jenkins when there is a DC change as
it causes:
1. thundering-herd issue when we start all jenkins at once for a tenant
update
2. Unnecessary wakes up jenkins that is sleeping
3. Restarts jenkins even if a build could be in progress
Issues: openshiftio/openshift.io#4306
> Do not start jenkins on changes to DC

- auth/service.go
- sentry/sentry.go
There are two small improvements:
* in case of `NewUnauthorizedError` there was reported only the text `Could not resolve user token` without any additional information. I've attached the error that caused the failure to the message.
* in case of other errors than the internal ones, there was reported `error.stringError` instance. I've replaced it by wrapping the created message into the original error
> chore: improve sentry errors

- Makefile
- environment/service.go
- environment/service_test.go
- environment/template.go
- environment/templates/fabric8-tenant-che-mt.yml
- environment/templates/fabric8-tenant-che-quotas.yml
- environment/templates/fabric8-tenant-che.yml
- environment/templates/fabric8-tenant-jenkins-quotas.yml
- environment/templates/fabric8-tenant-jenkins.yml
- main.go
This PR adds `version-quotas` label to all objects in both `-che*-` and `-jenkins-` templates. This label contains version (latest commit `SHA`) of an associated quotas file.
Fixes: #652
> feat(#652): introduce version-quotas label in che and jenkins templates

- cico_setup.sh
When there is a PR that changes any of the templates, then the script will add a comment looking like:
This PR depends on: https://github.com/openshiftio/openshiftio-cico-jobs/pull/835 that enables an access to the necessary secret token
> Add comment redirecting to _tenant page to every PR changing a template

- auth/service.go
- auth/service_test.go
- controller/tenant.go
- test/data/token/auth_resolve_user.yaml
Changes proposed in this PR:
* rename both `OpenshiftUsername` and `OpenShiftUserToken` to `OpenShiftUsername` and `OpenShiftUsername` with capital "S" in the word "OpenShift"
* Use `TenantToken` object to retreive info from the token
* Store Tenant ID in `User` object - will be used in cases when we need only the tenant ID so we don't have to fetch user information from auth
> chore: use TenantToken to get info from JWT token & store ID in user

- auth/service_test.go
- cluster/service_test.go
- controller/tenants_test.go
- environment/service_test.go
- environment/template_test.go
- openshift/apply_test.go
- openshift/init_tenant_test.go
- openshift/process_template_test.go
- sentry/sentry_test.go
- test/config.go
- test/doubles/test_doubles.go
This PR moves:
* all test functions related to configuration and environments to `test` package (to `config.go` file)
* `setTemplateVersions` function to `testdoubles` package
the reason is to avoid cyclic package dependency in the future and to allow using `setTemplateVersions` in more tests/packages
> chore: move test functions to separated files/packages

- cluster/service.go
- cluster/whoami.go
- cluster/whoami_test.go
This PR moves the "whoami" logic to `cluster` package. There are two reasons:
* the logic is used only there
* avoid cyclic package dependency in future
> chore: move whoami logic to cluster

- controller/tenant.go
- environment/template.go
- environment/template_test.go
- migration/migration.go
- migration/sql-files/006-add-ns-base-name-column-to-tenant.sql
- migration/sql-files/006-add-ns-username-column-to-tenant.sql
- openshift/apply_test.go
- openshift/clean_tenant.go
- openshift/init_tenant.go
- openshift/init_tenant_test.go
- openshift/process_template.go
- openshift/process_template_test.go
- tenant/repository.go
- tenant/repository_test.go
- tenant/tenant.go
This PR introduces `nsUsername` in `tenant` table. It is used as a base-name (eg. `johny`) for namespace names. When a new tenant is being created, then it checks if there is some tenant or namespace that the same base-name already uses. If there is some, then it appends a number to the name starting with number 2 (eg. `johny2`) and checks for any conflict again.
> fix(#674): introduce nsUsername used as base-name for namespace names

- controller/tenant.go
- controller/tenant_test.go
- tenant/repository_test.go
- tenant/tenant.go
- test/testfixture/testfixture.go
- update/update_minishift_test.go
- update/update_test.go
as part of an attempt to lower the number of changes in the huge refactoring [PR](https://github.com/fabric8-services/fabric8-tenant/pull/673), I'm bringing one smaller part as a separated PR.
This one introduces `NamespaceState` as an enum used for namespace states
> use enum NamespaceState for states stored in namespaces

- controller/tenant.go
- controller/tenant_test.go
- environment/service.go
- environment/service_test.go
- environment/type.go
- openshift/apply.go
- openshift/init_tenant.go
- openshift/init_tenant_test.go
- openshift/process_template.go
- tenant/repository.go
- tenant/repository_test.go
- tenant/tenant.go
- tenant/tenant_test.go
- test/doubles/test_doubles.go
- test/testfixture/make_functions.go
- test/testfixture/testfixture.go
- update/update.go
- update/update_test.go
- update/versions.go
as part of an attempt to lower the number of changes in the huge refactoring [PR](https://github.com/fabric8-services/fabric8-tenant/pull/673), I'm bringing one smaller part as a separated PR.
This one replaces `NamespaceType` by `environment.Type` and uses it in all cases where the code refers to the type of environment/namespace
> create environment.Type and use it instead of NamespaceType

- sentry/sentry.go
- sentry/sentry_test.go
when context is not set (in case of a triggered cluster-wide update) then sentry should not panic
> fix: don't panic when context is nil and error is logged

- controller/update.go
- controller/update_test.go
- design/update.go
- update/update.go
When `status` is `updating` and `last_time_updated` is later than withing the timeout, then `/api/update` endpoint returns 409 with a message explaining why conflict
> feat: /api/update returns conflict when an ongoing update is detected

- controller/tenants_test.go
- controller/update_test.go
- openshift/init_tenant_test.go
- tenant/repository_test.go
- test/testfixture/testfixture.go
- update/update.go
- update/update_test.go
before executing the automated tenant update of a particular namespace then it checks whether is outdated or failed.
fixes: #718
> issue(#718): update only outdated or failed namespaces

- configuration/configuration.go
- controller/update_test.go
- update/update.go
- update/update_minishift_test.go
- update/update_test.go
This PR makes the tenants update slower to avoid capacity issues while running it in prod.
* do not run the tenant updates concurrently
* wait for 4 seconds after a single tenant update
This PR is a result of a discussion with @pbergene
Fixes: #720
> issue(#720): make cluster-wide tenants update slower

- controller/update.go
- controller/update_test.go
- design/update.go
- tenant/repository.go
- tenant/repository_test.go
When GET to `api/update` is called, then the response (apart from the information about an ongoing update) contains also a number of outdated tenants (that are going to be updated) `to-update`. 
It supports limitation to both env type and master URL.
Fixes: #731
> feat(#731): return number of outdated tenants

- openshift/callback.go
- openshift/callback_test.go
- openshift/service_test.go
when tenant checks for the presence of namespaces (before their creation) then it treats 403 as not present because OS returns 403 for projects that are not present
> when checks for presence of namespaces then 403 treat as it is not present

- openshift/callback.go
- openshift/callback_test.go
- openshift/endpoints.go
- openshift/service_test.go
- test/gock_matchers.go
when tenant checks that namespace was created, it should use the same token as was used for creation
> fix: for checking if ns was created use same token as for creation

- openshift/callback.go
- openshift/callback_test.go
- openshift/endpoints.go
- openshift/methods.go
- openshift/service_test.go
handle correctly conflicts for resource quotas (mainly the part of removing `afterdocallback`) otherwise it doesn't redo and just fails
>  fix: handle correctly conflicts for resource quotas 

- openshift/callback.go
- openshift/callback_test.go
- openshift/endpoints.go
- test/doubles/test_doubles.go
wait until PVC is removed or set to terminating state otherwise the following POST request doesn't detect that should be in terminating state but the state hasn't been set to that because the tenant service is too fast and OS is too slow
> fix: wait until PVC is removed or set to terminating state

- openshift/callback.go
- openshift/callback_test.go
- openshift/endpoints.go
just try to wait until is removed and don't fail, otherwise, the whole reset more likely fails because OS is too slow
add printing instead of logging warnings
raise number of retries
> fix: just try to wait until is removed and don't fail

- openshift/callback.go
- openshift/callback_test.go
- openshift/service_test.go
reset result when either 404 or 409 is ignored to not be checked in followings callbacks
make printing of the warnings shorter
> fix: reset result when either 404 or 409 is ignored

- environment/template.go
- openshift/action.go
- openshift/action_test.go
- openshift/callback.go
- openshift/callback_test.go
- openshift/endpoints.go
- openshift/methods.go
- openshift/methods_whitebox_test.go
- openshift/service.go
- openshift/service_test.go
- openshift/types_test.go
- test/doubles/test_doubles.go
- test/gock_matchers.go
* clean should delete all resources (not only those that are in templates), otherwise, some objects created after the provisioning can also stay there
* replaced printing on stdout by logrus warning
* increased waiting timeout for pvc being removed
* introduced `OperationSet` abstraction - it's a map of required action applied to set of objects - will be very useful for next features that are going to be implemented
> fix: clean should delete all resources (not only those that are in templates)

- controller/tenant_test.go
- openshift/action.go
- openshift/action_test.go
- openshift/callback.go
- openshift/endpoints.go
- openshift/methods.go
- openshift/methods_whitebox_test.go
- openshift/service_test.go
- test/doubles/test_doubles.go
when doing clean action, instead of calling "delete all" endpoints (eg.  [delete all PVC](https://docs.openshift.com/container-platform/3.7/rest_api/api/v1.PersistentVolumeClaim.html#Delete-api-v1-namespaces-namespace-persistentvolumeclaims) ) for `all,pvc,cm` kinds retrieve all available objects of that kind for every namespace and delete the objects one by one. 
Fixes: #749
>  fix(#749): don't use "delete all" endpoints and clean all object one by one

- openshift/action.go
- openshift/action_test.go
- openshift/callback.go
- openshift/callback_test.go
- openshift/endpoints.go
- openshift/methods.go
- openshift/methods_whitebox_test.go
- openshift/service_test.go
- test/doubles/test_doubles.go
adds a new method `EnsureDeletion` (used only for deletion) that gets the objects and waits for 15s for their removal (response code is 404 or 403). This is added mainly to wait for pods/replicacontroller removal to avoid race conditions in OS
Fixes: #751,  #749
> fix(#751): when doing clean wait until objects are removed

- environment/templates/fabric8-tenant-jenkins.yml
This will add a new configmap in jenkins namespace for
openshift login plugin.
Previously there were default roles in openshift-login plugin
and they can't be configured. Because of that we were using
a fork of upstream login plugin with roles configuration
according to our use case.
Now, a patch has been added in upstream login plugin through
which we can configure roles by providing a configmap
This patch will add the same configmap which will be used
by openshift-login plugin to configure roles.
We will deprecate our fork of login plugin and will move to
upstream version.
From image, we have removed our fork binary and used upstream
using this patch
fabric8io/openshift-jenkins-s2i-config#234
This will fix openshiftio/openshift.io#4608
> Add configmap in jenkins namespace for openshift-login plugin

- controller/tenant.go
- controller/tenant_test.go
- main.go
* When there is an error containing `pq: duplicate key value violates unique constraint` returned on the creation of tenant entity in DB, then it means that there is already one created so it should return a conflict (this happens when there are two POST call at the same time)
* construct TenantUpdater in main.go correctly to not panic
> fix: returns conflict on duplicate key errors&set params in updater

- openshift/types.go
- openshift/types_test.go
don't modify che edit rights (add/remove) when request context is nil - in case of cluster update
> fix: don't modify che edit rights when context is nil

- controller/tenant.go
- controller/tenant_test.go
- controller/tenants_test.go
- controller/update_test.go
- test/doubles/controller.go
as preparation for adding a new metrics ([ODC-238](https://jira.coreos.com/browse/ODC-238)) and creating tests for it, it is necessary to move the test functions that prepare an environment for testing controllers to some common package (`testdoubles`) to make it reusable in metrics tests. 
One part also slightly changes error handling to make it easier for the metrics to report potential problems
For more information on the motivation see this pr: https://github.com/fabric8-services/fabric8-tenant/pull/763
> chore: move test controller preparation functions to testdoubles package to make it reusable & modify error handling

- controller/tenant.go
- controller/tenant_test.go
temporary workaround for https://github.com/redhat-developer/rh-che/issues/1296#issuecomment-475149410
It disables the check of unprovisioned namespaces for already provisioned tenants. This allows us to have an account with only two namespaces (che and user) provisioned
> disable check of unprovisioned namespaces for already provisioned tenant

- Gopkg.lock
- controller/tenant.go
- main.go
- metric/metric.go
- metric/metric_test.go
adds monitoring metrics that record number of provisioned/updated/cleaned tenants.
Every record contains information whether the action was successful or failed. In addition, updated/cleaned records also contain namespace base name of the affected tenant.
Implements: [ODC-238](https://jira.coreos.com/browse/ODC-238)
Builds on top of https://github.com/fabric8-services/fabric8-tenant/pull/762, the actual commit that implements the metrics is this c4573fd
> feat(ODC-238): add tenant related monitoring metrics 

- controller/tenants_test.go
- openshift/action.go
- openshift/action_test.go
When a tenant is going to be deleted, then remove also DB records of namespaces of old unsupported namespaces (run, stage, jenkins) to not fail when checking if all namespaces were removed.
> fix: when tenant is deleted,remove namespaces of unsupported types from DB

- controller/tenants.go
- metric/metric.go
- metric/metric_test.go
* adds metric monitoring (counting) tenants deletion
* use constants for the names of metrics
* add test checking that `/metrics` endpoints exposes the new metrics
> feat(ODC-238): add metric monitoring tenants deletion

- Gopkg.lock
- controller/tenant_test.go
`ctx.Conflict()` doesn't return an error (unless something bad happens), so the original error check was useless. Instead of it, read the response code from the context.
> fix(test): read error and response code from context

- Gopkg.lock
- controller/tenants_test.go
- openshift/callback.go
- openshift/callback_test.go
When tenant service tries to delete namespaces and OS returns 403, then it should be considered as already removed and the error ignored.
> fix: ignore 403 while deleting namespaces

- migration/migration.go
- migration/sql-files/010-delete-run-stage-jenkins.sql
as a migration step, it deletes `run`, `stage` and `jenkins` namespaces from the tenant DB
> chore(ODC-125): delete run, stage, jenkins namespaces from tenant DB

- environment/service_test.go
- environment/template.go
- environment/template_test.go
- environment/templates/fabric8-tenant-user.yml
the userName that is used for namespace provisioning shouldn't start nor end with dash and shouldn't be a number. If it doesn't comply with these conditions, then it gets either `os` prefix or `io` suffix or both.
Also changed the failing User template so the problematic annotation is in a format of string (similarly as is done in Che template)
> fix(CRT-355): username shouldn't be a number nor start nor end with dash

- controller/tenant.go
- controller/tenant_test.go
- environment/template.go
- test/doubles/controller.go
when the user already exists but with a non-compliant nsBaseName and it has no provisioned namespaces then it updates the nsBaseName to the compliant one
> fix(CRT-355): update non-compliant nsBaseName for existing users when no namespace is provisioned

- environment/templates/fabric8-tenant-che-mt.yml
- environment/templates/fabric8-tenant-che-quotas.yml
- environment/templates/fabric8-tenant-user.yml
use all vars as strings in all templates because not only annotations have a problem with a username containing only numbers, but also RoleBindings. Yes, I'm stupid that I didn't realize it before :-/
> fix(CRT-355): use all vars as strings in all templates

- environment/templates/fabric8-tenant-che-quotas.yml
Since there is ClusterResourceOverride admissionConfig plugin in OSO clusters with limitCPUToMemoryPercent=200 (or so) we need to set the max CPU limit per Pod to x2 of what we have for memory.
It seems that CPU limits in all the containers in a Pod are set (overridden) to 200% of the memory limits.
For example if the summery of all the memory limits of all the containers of a Pod is 7Gi then the summery of the CPU limits of those containers will be 14 cores. So we have to set the LimitRange for a Pod to 14 cores too. Otherwise the summery of the containers limits will be bigger than the max CPU allowed by the LimitRange.
See https://docs.openshift.com/container-platform/3.11/admin_guide/overcommit.html#configuring-masters-for-overcommitment for details.
> Set max CPU limit to 14 cores per Pod
