fabric8-services/fabric8-tenant

openshift/process.go
openshift/process_test.go

Caused trouble for inlined json in yaml values..

Remove eager search/replace of variable markers

---

openshift/apply.go
openshift/apply_test.go

Add simple sort based on Kind

---

controller/tenant.go
design/tenant.go
tenant/service.go

GET /api/tenant
Get a tenants namespaces, cluster and state info

Expose tenant state API

---

controller/tenant.go
design/tenant.go

* Currently does _not_ update tenant namespace values

Add PATCH support to api/tenant to trigger an update

---

Dockerfile.deploy
openshift/init_tenant.go

Attempt to avoid possible update conflicts due to old versions
Related #122

Add overwrite and force to oc apply command

---

.gitignore
openshift/init_tenant.go
openshift/whoami.go
template/generate.go

add an enviroment variable to use kubernetes versions of the templates

fix(kubernetes): lets support kubernetes

---

Dockerfile.deploy

Fixes upstream issue openshift/origin#15017
Related #122

Add upstream master local build of oc

---

openshift/apply.go
openshift/init_tenant.go

RoleBindingRestrictions need to be applied before RoleBinding
Fixes #122

Reorder the templates from fabric8-online

---

openshift/process.go
openshift/process_test.go

Avoids templates being html/xml safe escaped

Replace html/template with simple RegExp replace

---

glide.lock

Related to fabric8-services/fabric8-wit#1496

Update to latest fabric8-wit

---

controller/tenant.go
glide.lock
glide.yaml
openshift/init_tenant.go
openshift/kube_keycloak.go
openshift/kube_token.go
template/generate_test.go

as we use KC to login to jenkins on kubernetes versus the inbuilt OpenShift OAuth approach
so we need to add each jenkins tenant redirect URI to KeyCloak

for kubernetes lets add a redirectURI for jenkins tenants

---

controller/tenant.go

Remove user restriction. Rollout to all users.

---

controller/tenant.go
controller/tenant_kube.go
design/tenant.go
design/tenant_kube.go
main.go
openshift/init_tenant.go
openshift/kube_keycloak.go

we need to wait for the Jenkins service endpoint to be visible so we can
register it into KeyCloak for new tenants on kubernetes so lets add a
little REST API we can poll from the UI for kubernetes

lets add an API to check if the kubernetes tenant is connected

---

glide.lock
glide.yaml
main.go

* unifies fields.time units
* logs requests on error
Fixes #217

Update to latest logging v

---

Dockerfile.deploy

Update oc client to 3.6.0

---

migration/migration.go
migration/sql-files/002-remove-dup-ns.sql

Remove duplicate namespace entries

Clean up tenant database

---

openshift/init_tenant.go
openshift/kube_keycloak.go
openshift/process_template.go
openshift/process_template_test.go

Related to openshiftio/openshift.io#619

Replace all non a-z0-9 chars in username to use as basename

---

configuration/configuration.go
main.go
openshift/config.go
openshift/init_tenant.go
openshift/kube_token.go
openshift/process.go

- add config to help test in development tenant YAML
- on kubernetes replace parameters to get pipelines pushing to docker registry

make testing development YAML easier and get pipelines working on plain kubernetes

---

openshift/apply.go
template/generate_test.go

Related to openshiftio/openshift.io#665

Verify templates match Status API req

---

controller/tenant.go
controller/tenants.go
controller/tenants_test.go
design/tenant.go
glide.lock
glide.yaml
keycloak/context.go
keycloak/context_test.go
keycloak/openshift.go
keycloak/publickey.go
keycloak/publickey_test.go
main.go

Only fabric8-jenkins-idler SA Token is valid
Related to openshiftio/openshift.io#1245

Add API for tenant lookup by ID for Service Accounts  

---

main.go

Related to openshiftio/openshift.io#1245

Mount tenants REST endpoint

---

OpenShiftTemplate.yml

Related to openshiftio/openshift.io#1377

Update number of Replicas to > 1

---

OpenShiftTemplate.yml
configuration/configuration.go
f8tenant.secrets.yaml
openshift/process_template.go

Related to redhat-developer/rh-che#377

Expose CHE_MULTITENANT_SERVER and OSIO_TOKEN to templates

---

controller/tenant.go
controller/tenant_kube.go
controller/tenants_test.go
docker-compose.yml
glide.yaml
tenant/service.go
tenant/service_test.go
test/gormsupport/cleaner.go
test/gormsupport/db_test_suite.go
test/resource/require.go
test/testfixture/customize_entity_funcs.go
test/testfixture/make_functions.go
test/testfixture/recipe_funcs.go
test/testfixture/testfixture.go

Include TextFixture lib to test the DB services (#471)

---

template/generate_test.go

Signed-off-by: David Festal <dfestal@redhat.com>

update parameter number

---

openshift/apply.go
template/generate_test.go

Missing type caused init to fail on Unknown Type.
Add Type check in test suite.

Add type Job to REST mapping

---

openshift/init_tenant.go

This reverts commit ee1186ddc8238b6cf363b0819b4cc81c65c780e4.

Revert "Add temp debug info to investigate Che Migration issue (#513)"

---

controller/tenant.go
controller/tenants.go
controller/tenants_test.go
design/tenant.go
glide.lock
glide.yaml
main.go
token/clusters.go
token/clusters_test.go
token/token.go

* console url
* app dns
* metrics url
Related to fabric8-services/fabric8-wit#1859
Related to fabric8-services/fabric8-tenant#515

Expose additional cluster data per namespace

---

token/clusters.go
token/clusters_test.go

Related to openshiftio/openshift.io#2122

Add better equality check for Cluster URL between User and Cluster API

---

OpenShiftTemplate.yml
configuration/configuration.go
f8tenant.secrets.yaml

Allow setting jenkins root URL directly from template,

Allow setting jenkins root url

---

main.go

Avoid nil transport in Openshift Config

---

controller/tenant.go

Log Request/Response on unhandled status codes during init

---

controller/tenant.go
openshift/apply.go

ResourceQuota resource has a async nature so attempting to fill the quota
before the quota has been applied cause 403 Forbidden errors.
Enter a retry get loop after create of ResourceQuota to wait for it
to finish.

Add a retry loop to validate ResourceQuotas has been applied

---

controller/tenant.go

Log req/res on all init requests

---

controller/tenant.go

Increase sleep to 5s after ProjectRequest to wait for async auth

---

controller/tenant.go
controller/tenants_test.go
design/tenant.go
openshift/clean_tenant.go
tenant/repository.go
tenant/repository_test.go

Removes the tenant from cluster and TenantDB

Add support for remove=true to tenant DELETE

---

controller/tenant.go
controller/tenants_test.go
tenant/repository.go
tenant/repository_test.go

Avoid UPSERT on Tenant Init to only perform init once

---

controller/tenant.go
openshift/apply.go
openshift/init_tenant.go

Related to openshiftio/openshift.io#2634

Log requested update template

---

migration/migration.go
migration/sql-files/004-index-tenants-search.sql

Fixes openshiftio/openshift.io#2671

Add index to namespaces (name, master_url) for reverse namespace lookup

---

tenant+pmcd.sh

Adapt to https://sourceware.org/git/?p=pcpfans.git;a=commitdiff;h=1f0a1f90bc8e01b5b28810ecd6a8cf505969f243

fix pcp pmdaprometheus configuration line

---

controller/tenant.go

Include cluster URL in logs (#575)

---

Jenkinsfile

recently fixed https://github.com/openshiftio/openshift.io/issues/3324, fixed the master builds https://jenkins.cd.test.fabric8.io/job/fabric8-services/job/fabric8-tenant/job/master/224/console

fix the cd pipeline

---

Makefile
controller/tenants_test.go
design/tenant.go

Fixes https://github.com/openshiftio/openshift.io/issues/3445

API to delete a user from Tenant should be DELETE. Not GET

---

.make/Makefile.lnx
.make/Makefile.win
Dockerfile.builder
Makefile

Remove HG from build requirements (#592)

---

.make/test.mk
Gopkg.toml
README.adoc
cico_build_deploy.sh
cico_run_tests.sh
cico_setup.sh
codecov.yml

Fixes openshiftio/openshift.io#3559

Support for codecov.io (OSIO#3559)

---

openshift/apply.go

Related fabric8-services/fabric8-tenant-che#111

Add init support for kind Role

---

OpenShiftTemplate.yml

https://ci.centos.org/view/Devtools/job/devtools-fabric8-tenant-build-master/437/console
verified locally by `oc process -f ./OpenShiftTemplate.yml`

fix: use correct indentation in OpenShiftTemplate.yml

---

environment/service.go
environment/service_test.go
environment/service_whitebox_test.go

otherwise, it fails with `panic: assignment to entry in nil map`

fix: initialize map before assigning to an entry in it

---

environment/templates/fabric8-tenant-jenkins.yml

Create an empty list for triggers.

Make sure triggers are not firing up

---

environment/templates/fabric8-tenant-jenkins.yml

Allow java.io.File.isDirectory() so that we would be able to check in
the pipeline if we have create nodes directory
https://github.com/openshiftio/openshift.io/issues/4020

Issue #4020 Allow isDirectory() operation

---

OpenShiftTemplate.yml

https://github.com/openshiftio/saas-openshiftio/pull/1170

change reading of F8_AUTOMATED_UPDATE_ENABLED var to be set as param

---

Dockerfile.builder

See openshiftio/openshift.io#4618

Switch build to epel release

---

controller/tenant.go
controller/tenant_minishift_test.go
openshift/clean_tenant.go
openshift/init_tenant.go

fix(#708): wait for finishing tenant reset/update and return errors

---

openshift/init_tenant.go
openshift/init_tenant_test.go

recreate namespace only when 409 or 403 is returned for any of the types: namespace/projectrequest/pvc
for the rest of the types just remove the particular object
fixes: #722

fix(#722): recreate when is conflict for namespace,projectrequest or pvc

---

controller/tenant.go
openshift/init_tenant.go

when the update fails with one or more errors, then don't recreate and just wait for 10s and try to update it one more time.
fixes: #724

fix(#724): don't recreate when update fails

---

Gopkg.lock
Gopkg.toml
controller/tenants.go

... to get more info on why I have a lot of errors like:
```
{"GET":"/api/tenants/5402e606-e5e7-4abb-b38a-1e537010e27f","action":"show","ctrl":"TenantsController","from":"10.131.6.1","identity_id":"e7eff3e8-229b-4e9f-b50b-aa2f505e5afa","level":"info","msg":"request started","pkg":"github.com/fabric8-services/fabric8-tenant/vendor/log.LogRequest.func1","req_id":"sxwmx0zhaQ-169780","time":"2019-01-14 04:18:35"}
{"error_type":{},"file":"/tmp/go/src/github.com/fabric8-services/fabric8-tenant/controller/tenants.go","func":"github.com/fabric8-services/fabric8-tenant/controller.(*TenantsController).Show","identity_id":"e7eff3e8-229b-4e9f-b50b-aa2f505e5afa","level":"error","line":52,"msg":"error while looking-up tenant record","pid":1,"pkg":"github.com/fabric8-services/fabric8-tenant/controller"," …
```

when no tenant is found then log SA name in the error

---

controller/update.go
controller/update_test.go
dbsupport/transaction.go
test/update/doubles.go
update/repository.go
update/repository_test.go
update/update.go
update/update_test.go

moving transaction logic to a separated package so it is usable in the future

move transaction support to separated package-to be usable in future

---

environment/templates/fabric8-tenant-che-quotas.yml

Decrease minimal RAM allowed for che containers
issue: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2511
/cc @ibuziuk

Decrease minimal RAM allowed for che containers

---

tenant/repository.go
tenant/repository_test.go
update/update.go
update/update_test.go

When no `cluster_url` is set as a limit for the cluster-wide update, then the updater is executed for the list of all clusters that contain outdated tenants in parallel.
fixes: #757

feat(#757): update clusters in parallel

---

controller/tenant.go
controller/tenant_test.go

reverting eff7c1d but keeping fixes of assertions of the conflict errors

activate check for missing namespaces (revert eff7c1d)

---

controller/tenant_test.go
test/doubles/controller.go

an attempt to avoid these errors: https://ci.centos.org/view/Devtools/job/devtools-fabric8-tenant-build-master/532/consoleFull

fix(test): use persisted gock mocks in parallel tests

---

environment/templates/fabric8-tenant-che-mt.yml
environment/templates/fabric8-tenant-user.yml

specify annotations as strings otherwise it will fail for the requester when it contains only numbers

fix(CRT-355): specify annotations as strings
